### ISSUE TITLE
Is MQTT on a Web Socket supported now ?

### ISSUE THREAD

**Issue by srijiths** [evokly/kafka-connect-mqtt#15]
Is the project supports connecting to a web socket other than tcp ?

**Comment by moperacz** [comment]
for sure there is support for plain TCP socket and TLS socket (with optional mutual auth)

but underneath it is http://www.eclipse.org/paho/

and they support WebSockets (http://www.eclipse.org/paho/clients/java/)  

so You can try to connect to `wss://your-ws-broker/mqtt` and then tell us if it has WebSocket support :wink:

**Comment by srijiths** [comment]
@moperacz Yes Paho Mqtt has web socket support. By replacing tcp:// with ws:// in kafka-connect-mqtt wont work. But , i think there is no point in including one ws connector in kafka-connect-mqtt. A generic kafka-connect-websocket would be feasible for that. So closing this issue.
