### ISSUE TITLE
Time out and Connection Alive properties

### ISSUE THREAD

**Issue by srijiths** [evokly/kafka-connect-mqtt#16]
![01](https://cloud.githubusercontent.com/assets/1046319/16556447/b60da32c-41f7-11e6-8e60-f784ef97e75f.png)
I set connection alive property less than the connection time out. But still connection is getting timed out. Pics attached
![01](https://cloud.githubusercontent.com/assets/1046319/16556420/8dc2710e-41f7-11e6-828d-406176255d93.png)

**Comment by moperacz** [comment]
it seems that it can not connect to server... which branch you are using?

and also is it the same "error" that #17 ?

**Comment by srijiths** [comment]
@moperacz No this is not the same error. I updated to Kafka_10 and let me try this connection time out  and update.

**Comment by srijiths** [comment]
@moperacz kafka_10 branch is working fine now . Closing this issue.
