### ISSUE TITLE
Custom mqtt properties not overriding the default properties

### ISSUE THREAD

**Issue by srijiths** [evokly/kafka-connect-mqtt#17]
Still its taking the default properties set in MqttSourceConnectorConfig.

**Comment by moperacz** [comment]
can you please share your `.properties` file (of course obfuscate sensitive data)

in `kafka_10` branch props names were changed

**Comment by srijiths** [comment]
@moperacz Please see the property file

![screenshot from 2016-07-06 11 43 03](https://cloud.githubusercontent.com/assets/1046319/16609157/45ef7eac-436f-11e6-8ead-6938f2845525.png)

**Comment by srijiths** [comment]
@moperacz Have you got a chance to test this ?

**Comment by moperacz** [comment]
Sorry for the delay, you are using properties from the older version in the new version. I've committed sample props file, please check it out.

For Your case it should be:

```properties
kafka.topis=test1
mqtt.topic=test1
mqtt.server_uris=tcp://xzy:1883
mqtt.keep_alive_interval=20
mqtt.connection_timeout=100
```

**Comment by srijiths** [comment]
@moperacz Thank you. It works !
