### ISSUE TITLE
Configuration to format a message - BYTES / STRING schema ?

### ISSUE THREAD

**Issue by srijiths** [evokly/kafka-connect-mqtt#18]
@moperacz , It would be a good feature , if we can control the formatting of messages inside your DumbProcessor class. 
```
    @Override
    public SourceRecord[] getRecords(String kafkaTopic) {
        return new SourceRecord[]{new SourceRecord(null, null, kafkaTopic, null,
                Schema.STRING_SCHEMA, mTopic,
                Schema.BYTES_SCHEMA, mMessage.getPayload())};
    }
```
Schema.BYTES_SCHEMA or Schema.STRING_SCHEMA for a message is based on a configuration.

**Comment by moperacz** [comment]
you can create your processor which implements `MqttMessageProcessor` interface and point your .properties to make use of your processor (we are doing this in-house) 😉
