### ISSUE TITLE
how multiple topics are supported with this kafka-connect-mqtt?

### ISSUE THREAD

**Issue by balag1986** [evokly/kafka-connect-mqtt#22]
This plugin works very well if mqtt publishes messages on a single topic and kafka consumes those messages on the same topic. Since we use mqtt.properties file and the topics are defined uniquely inside it, is there an option to make kafka-connect-mqtt to listen on multiple topics?

**Comment by moperacz** [comment]
you can use a wildcard in topic selection in .properties, and then in your processing class you can behave differently in respect of topic
