### ISSUE TITLE
Thread safety when using LinkedList as Queue

### ISSUE THREAD

**Issue by alukito** [evokly/kafka-connect-mqtt#5]
Hello, I'm new to kafka and I'm trying to use kafka with mqtt as source. 

I found that in [this code](https://github.com/evokly/kafka-connect-mqtt/blob/master/src/main/java/com/evokly/kafka/connect/mqtt/MqttSourceTask.java#L41), you're using `java.util.LinkedList` as the queue implementation. The queue will be accessed by multiple threads, one of them is mqtt thread. `java.util.LinkedList` is not thread safe. 

I'm suggesting to use `java.util.concurrent.LinkedBlockingQueue` as it is thread safe and it supports [`take`](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/LinkedBlockingQueue.html#take%28%29) method that could wait the thread when the queue is empty. It eliminates the need to loop while queue is empty.

I could make a pull request if you'd like me to.

**Comment by moperacz** [comment]
Yeah, You are right. PR are more than welcome.

**Comment by alukito** [comment]
Hi, I'm sorry for late follow up with my pull request I promised. Thanks for the fix.
